
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Proyecto1;

/** CUP generated class containing symbol constants. */
public class sym1 {
  /* terminals */
  public static final int mayorq = 7;
  public static final int comilla = 22;
  public static final int figura = 5;
  public static final int nombre = 8;
  public static final int diseno = 6;
  public static final int tipo = 10;
  public static final int coma = 14;
  public static final int descripcion = 11;
  public static final int ext = 24;
  public static final int creditos = 25;
  public static final int pcoma = 15;
  public static final int num = 19;
  public static final int punto = 23;
  public static final int igual = 16;
  public static final int imagen = 9;
  public static final int EOF = 0;
  public static final int id = 20;
  public static final int slash = 21;
  public static final int destruir = 12;
  public static final int vida = 13;
  public static final int error = 1;
  public static final int llaveizq = 18;
  public static final int menorq = 2;
  public static final int llaveder = 17;
  public static final int config = 3;
  public static final int fondo = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "menorq",
  "config",
  "fondo",
  "figura",
  "diseno",
  "mayorq",
  "nombre",
  "imagen",
  "tipo",
  "descripcion",
  "destruir",
  "vida",
  "coma",
  "pcoma",
  "igual",
  "llaveder",
  "llaveizq",
  "num",
  "id",
  "slash",
  "comilla",
  "punto",
  "ext",
  "creditos"
  };
}

