
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Proyecto1;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int cescenario = 15;
  public static final int ancho = 3;
  public static final int cheroes = 27;
  public static final int personajes = 17;
  public static final int cmeta = 24;
  public static final int cextras = 22;
  public static final int fondo = 4;
  public static final int mayorq = 6;
  public static final int meta = 25;
  public static final int coma = 7;
  public static final int igual = 9;
  public static final int pder = 10;
  public static final int cpersonajes = 16;
  public static final int alto = 5;
  public static final int villanos = 29;
  public static final int suelo = 21;
  public static final int escenario = 14;
  public static final int EOF = 0;
  public static final int cvillanos = 28;
  public static final int menorq = 2;
  public static final int nombre = 13;
  public static final int error = 1;
  public static final int csuelo = 20;
  public static final int pcoma = 8;
  public static final int cparedes = 19;
  public static final int rp = 12;
  public static final int bonus = 33;
  public static final int id = 35;
  public static final int cbonus = 32;
  public static final int armas = 31;
  public static final int heroes = 26;
  public static final int pizq = 11;
  public static final int extras = 23;
  public static final int paredes = 18;
  public static final int carmas = 30;
  public static final int num = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "menorq",
  "ancho",
  "fondo",
  "alto",
  "mayorq",
  "coma",
  "pcoma",
  "igual",
  "pder",
  "pizq",
  "rp",
  "nombre",
  "escenario",
  "cescenario",
  "cpersonajes",
  "personajes",
  "paredes",
  "cparedes",
  "csuelo",
  "suelo",
  "cextras",
  "extras",
  "cmeta",
  "meta",
  "heroes",
  "cheroes",
  "cvillanos",
  "villanos",
  "carmas",
  "armas",
  "cbonus",
  "bonus",
  "num",
  "id"
  };
}

