
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Proyecto1;

/** CUP generated class containing symbol constants. */
public class sym3 {
  /* terminals */
  public static final int escenarios = 12;
  public static final int cescenarios = 13;
  public static final int id = 6;
  public static final int escenario = 3;
  public static final int slash = 10;
  public static final int orden = 8;
  public static final int pcoma = 7;
  public static final int num = 9;
  public static final int EOF = 0;
  public static final int menorq = 2;
  public static final int error = 1;
  public static final int nombre = 4;
  public static final int mayorq = 11;
  public static final int igual = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "menorq",
  "escenario",
  "nombre",
  "igual",
  "id",
  "pcoma",
  "orden",
  "num",
  "slash",
  "mayorq",
  "escenarios",
  "cescenarios"
  };
}

